export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const SET_EDIT = 'SET_EDIT';
export const SET_CURRENT = 'SET_CURRENT';
